name: 'pronto-annotate-action'
description: 'Action to read a pronto json report file and create github annotations'
author: 'Emilio'

inputs:
  reportPath:
    description: 'Pronto json report file'
    required: true

runs:
  using: node20
  main: dist/index.js
